Panic if LayersByClass returns nothing
emer/axon pull request #151
Opened 2023-02-01 00:02 UTC by siboehm

`LayersByClass` just caused me & Erdal to spend an hour pair-programming to figure out why ObjRec was broken after we updated Axon.
This is because `LayersByClass` just silently returns an empty list, if the passed string doesn't match anything.

The real fix would be to delete this function, and just keep `LayerByType`.
But for now, we just panic if it returns nothing.

2023-02-01 05:40 UTC, rcoreilly requested changes
There are no other cases where the axon / emergent codebase resorts to a panic for this kind of thing -- how about just emitting a log error message, which is what is typically done, e.g., in the case of params that don't match etc?  This is much "friendlier" overall while still clearly conveying the issue.

In which case, it would be useful to include more information about the nature of the error, why it happened, and in this case, what should be done to fix it.  e.g., 

"axon.Network LayersByClass for classes: %s did not include any layers -- for basic layer types, which have been renamed since v1.7, you should instead use LayersByType which takes the LayerTypes enum values instead of strings.  Otherwise, you have a mismatch in your SetClass vs the args used here."

2023-02-01 06:45 UTC, jedmccaleb commented
Much better to error than just emit an log message. In this case and when params don't match. This is basically type safety for your cfg files. very easy to miss the log message

2023-02-01 08:16 UTC, rcoreilly commented
One issue is that if you panic at every issue, it can take a while to iterate through them all.  Maybe better to have a mode switch for this?  Then you can set `axon.PanicOnErr = true` and get your panics when you want them?

2023-02-01 16:31 UTC, siboehm commented
I updated the error message to be more helpful. The problem with logging is that it's too easy to get lost once we're running things on infra. Other option would be to have the function return (val, error), but that'd required changing emer.Network

2023-02-02 08:08 UTC, rcoreilly commented
I definitely don't want the params case to panic for every error in params -- often there can be many when things are renamed or you are first setting things up, and iterating through each one is not going to be productive.  But I agree that once a model is in production mode, running on a server, you want the panic.

Therefore, I think the mode flag is the best solution.  It actually has to be in the emer library, because that is where params stuff happens.  Would be good to just have a simple wrapper API around `log` (Jed used some kind of existing package for something -- maybe this already has the option?  If not, certainly it exists somewhere) that makes it easy to switch between printing vs. panicing?

2023-02-02 20:59 UTC, jedmccaleb approved these changes

2023-02-02 21:16 UTC, siboehm commented
@rcoreilly can we merge this and deal with the Pattern thing in a different PR? This is purely for the LayerByClass function, with we've already stumbled over twice now, and this PR seems like a sane and fast fix.

2023-02-03 01:44 UTC, rcoreilly approved these changes

2023-02-03 01:44 UTC, merged