AddHip in hip_net.go for modular hip
emer/axon pull request #272
Opened 2023-07-13 22:49 UTC by zycyc

tested and compatible w/ hip.go in #270 @rcoreilly

2023-07-14 16:10 UTC, rcoreilly commented
with that many args, it probably makes more sense to use a HipConfig struct as the arg to this function.  Then you can add descriptions for the meaning of each arg.   also rebase or merge to current master.

2023-07-14 18:14 UTC, zycyc commented
should be good for review

2023-07-14 18:43 UTC, rcoreilly requested changes
* `In` should not be created here -- won't be used in most other models.
* projections from input(s) -> EC2 and back to conrtex etc will need to be made outside of this AddHip function -- this should just make the hip proper.
* Ec2 -> EC2 etc -- keep it consistent -- EC should always be uppercased in general.
* add `def:""` default values for all fields that have clear defaults
* Theta*, MemThr are not needed for the network config -- how about we just move those to LogConfig or a HipStatsConfig if using a common method?  Can call this HipNetConfig for better specificity.

2023-07-17 17:45 UTC, rcoreilly reviewed
removing those commented lines is the only change -- everything else looks good!

2023-07-17 17:45 UTC, rcoreilly commented on axon/hip_net.go
> +	// ECPctAct     float32 `desc:"percent activation in EC pool"`
just cut..

2023-07-17 17:47 UTC, rcoreilly commented
also don't forget to update to master (rebase  or merge)

2023-07-17 17:56 UTC, zycyc commented
done and rebased.

2023-07-17 18:07 UTC, rcoreilly approved these changes

2023-07-17 18:07 UTC, merged